site_name: multiscannerDocs
pages:
- Overview: 'index.md'
- Architecture: 'arch.md'
- Use Cases: 'use-cases.md'
- Installation: 'install.md'
- Using MultiScanner:
    - 'Web Interface': 'use/web-ui.md'
    - 'Python API': 'use/python-api.md'
    - 'RESTful API': 'use/rest-api.md'
    - 'Analysis Modules': 'use/use-analysis-mods.md'
    - 'Analytics': 'use/use-analytics.md'
- Custom Development: 
    - 'Analysis Modules': 'custom/analysis-module.md'
    - 'Analytics': 'custom/analytics.md'
    - 'Storage Modules': 'custom/storage-module.md'
    - 'Example Module': 'custom/example.md'