site_name: multiscannerDocs
pages:
- Overview: 'index.md'
- Architecture: 'arch.md'
- Use Cases: 'use-cases.md'
- Installation: 'install.md'
- Using MultiScanner: 'using.md'
- Custom Development: 
    - 'Analysis Modules': 'custom/analysis-module.md'
    - 'Analytics': 'custom/analytics.md'
    - 'Storage Modules': 'custom/storage-module.md'
- Example Module: 'example.md'
